import Head from 'next/head'
import Nav from '../components/Nav'

import { setContent,selectContent, setUser, setToken, setLoggedIn } from '../state/cartSlice'
import { addProducts, setReady } from '../state/productsSlice'
import useSWR, { unstable_serialize } from 'swr'
import { Container } from '../components/Container'
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import {getCookie,setCookie} from 'cookies-next'
import store from '../state/store'
import RatingBar from '../components/RatingBar'
import ProductCont from '../components/ProductCont'
import ProductsContainer from '../components/ProductsContainer'
let initiated =false;


export default function Home()
{
    
   
   // let count = useSelector(selectContent)
    let dispatch = useDispatch();
    
    let [products,setProducts] = useState(store.getState().products.value);
   useEffect(()=>{ store.subscribe(()=>{
    //setProducts(store.getState().products.value)
    

})
if(!store.getState().products.ready)
fetch('http://localhost:23000/products')
.then((response)=> response.json())
.then((data)=>
{
    dispatch(setReady(true))
    dispatch(addProducts(data.result));
    setProducts(store.getState().products.value)

})})
let t = getCookie('topshop_userId');
let u = getCookie('topshop_token');
if(t != undefined && u != undefined)
{
  dispatch(setUser(u));
  dispatch(setToken(t));
  dispatch(setLoggedIn(true));
}
    // dispatch(setContent(<div className='flex flex-col ml-[15%] mr-0'>
    //  <div className='text-2xl font-bold mb-10'> Newest Products</div>
    //  <div className='flex gap-6'>
     
    //  </div>
    // </div>))    
    return(
        <div className="flex flex-col h-[100%]">
    <Head>
        <title>Top Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.svg" />
        <meta name='viewport' content='width=device-width,initial-scale = 0.9' />
    </Head>
    <Nav></Nav>
    <div className='text-2xl font-semibold w-fit ml-[10%] mr-auto mt-[12vh] mb-[2%] before:bg-red-600 before:w-20 before:h-20'>Newest Products</div>
  
     <ProductsContainer products={products} />  
    
    <div className='text-2xl font-semibold w-fit ml-[10%] mr-auto mt-[12vh] mb-[2%] before:bg-red-600 before:w-20 before:h-20'>Top Rated Products</div>
    {/* <div>{store.getState().products.value.length + " initiated : " + initiated}</div> */}
    {/* <div className='flex flex-col'>
    {store.getState().products.value.map((e)=>
   {
    <div className='text-4xl text-black'>{e.id + " name : " + e.name}</div>
   })}
    </div> */}
    <ProductsContainer products={products.filter((e)=> (e.rating-4)*5 > 4)}/>
    {/* <Container child={content} tailwind="w-[80%] h-full "></Container> */}
        
        </div>
    )
}
